# General Configuration
spring.application.name=healthcare-appointment-system
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate Second Level Cache Configuration
spring.jpa.properties.hibernate.cache.use_second_level_cache=true
spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.JCacheRegionFactory
spring.jpa.properties.hibernate.cache.use_query_cache=true

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=healthcare_db

# JWT Configuration
app.jwt.secret=185c2e85a1a840943f43cadb763ee8a97fcdf452a005c7e31e6ed13c8d56bb4c
# 24 hours
app.jwt.expiration=86400000

# Logging Configuration
logging.level.ps.exalt.healthcare_appointment_system.config.LoggingAspect=INFO
logging.level.org.hibernate=ERROR
logging.level.net.guides=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %msg%n